### ISSUE TITLE
Does the project have roadmap?

### ISSUE THREAD

**Issue by muirch** [octoman90/Genshin-Party-Builder#124]
Hi 👋

Do you have any roadmap for future updates or this application will no longer expand in functionality?

**Comment by octoman90** [comment]
Hello!
There's no definitive roadmap, but there are some things that I plan to do at some point.

- One of them is to completely rewrite the logic of the automatic suggestion algorithm. I still don't have a clear plan for it, but one of the changes I plan to introduce is to increase the number of roles from 3 (DPS, Support, Healer) to 7 (DPS, Burst DPS, Off-field DPS, Damage amp, Healer, Shielder and CC). Ideally, this should make the algorithm more intelligent.
- The other thing that I wanted to add is an option to import a list of characters from a JSON file in [GOOD format](https://frzyc.github.io/genshin-optimizer/#/doc). It's useful because it doesn't require manual input: projects like [Inventory Kamera](https://github.com/Andrewthe13th/Inventory_Kamera) can automatically get a list of owned characters and their constellation levels from the game.
- I also had an idea to create a separate page within the app that loads the same data that the suggestion algorithm does, and displays characters on a tier list of some kind. I can't imagine the result to not be complicated and/or cluttered, though, since the position of a character depends on the role and constellation (and hopefully more factors in the future). Such a page should make it easier to fine-tune the suggestions and allow users a more clear overview of how the algorithm works, without the need to hack it.

Suggestions are welcome too.

**Comment by muirch** [comment]
At first I wanted to suggest you use the [fanmade API](https://github.com/genshindev/api), but I see that the tools you have chosen are more powerful if used correctly.

So I have some ideas.
Instead of just algorithm that you have now, you can use some tools (like [brain.js](https://brain.js.org/#/) if you prefer js) for **AI analysis** of user team by parameters like:

- Heal per second (or something);
- Damage per second (DPS);
- Shield strength;
- Buffs provided;
- Constellation;
- Element;
- etc things.

And then make suggestions with gathered data from user (the chars user selected) and provide suggestions for the rest of the uncompleted team.

Another things that you may do is **make user possible to set weapon and artifacts for them** and change stats both for characters and their equipment. 

I know the proposed scope of work is very large, but with this it will be possible to create a very convenient tool for planning a team. I was going to do something like this a few months ago, but I don’t have enough time due to work to implement all the features I described. I think you will be able to implement a good tool!

**Comment by octoman90** [comment]
Well, full simulations are nice, but, honestly, simplicity is not necessarily a bad thing either. It wouldn't be an easy choice to give it up even if the amount of work needed to do so was minor.

And the amount of work for that would be large: at least as large as [Genshin Optimizer](https://github.com/frzyc/genshin-optimizer). It took them one and a half years to almost complete their app, with an active community of theorycrafters and several regular contributors.

There's just a niche for casual apps that rely on fairly subjective data and simple algorithms, and I'm fine with this project filling it.

**Comment by Primajin** [comment]
First of all thanks for this cool tool!

But please don't call the 30 or so lines of algorithm an "AI" that optimizes the team. As @muirch suggested either use a real AI or just call the tool a Genshin Party creator and optimizer or "suggestor" - there is no shame in that. Saying that there is an AI behind this on the other hand is not true in my opinion.

Not everything these days has to be an AI, your project is already cool the way it is 👍🏻
